name: Merge master branch to dev
on:
  pull_request:
    branches:
      - '*'
jobs:
  AutoComment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Thank you for raising your pull request.
      
            Test auto comment.


